package merge

import (
	"context"
	"fmt"
	"strings"
	"time"

	"stackit.dev/stackit/internal/app"
	"stackit.dev/stackit/internal/config"
	"stackit.dev/stackit/internal/engine"
	"stackit.dev/stackit/internal/git"
	"stackit.dev/stackit/internal/github"
)

// MultiStackPRCreator handles creating the multi-stack PR
type MultiStackPRCreator struct {
	ctx          *app.Context
	worktreeEng  engine.Engine
	worktreePath string
}

// NewMultiStackPRCreator creates a new PR creator for multi-stack merge
func NewMultiStackPRCreator(ctx *app.Context, worktreeEng engine.Engine, worktreePath string) *MultiStackPRCreator {
	return &MultiStackPRCreator{
		ctx:          ctx,
		worktreeEng:  worktreeEng,
		worktreePath: worktreePath,
	}
}

// GenerateMultiStackBranchName creates a unique branch name for the multi-stack PR
func GenerateMultiStackBranchName() string {
	return fmt.Sprintf("multi-stack/%s", time.Now().Format("20060102-150405"))
}

// GenerateMultiStackPRBody creates the PR description for multi-stack merge
func GenerateMultiStackPRBody(included []MultiStackInfo, excluded []MultiStackExcluded) string {
	var b strings.Builder

	b.WriteString("## Multi-Stack Merge\n\n")
	b.WriteString("This PR consolidates multiple stacks into a single atomic merge.\n\n")

	b.WriteString("### Included Stacks\n\n")
	for _, stack := range included {
		b.WriteString(fmt.Sprintf("- **%s** (%d branches)\n", stack.RootBranch, len(stack.AllBranches)))
		for _, branch := range stack.AllBranches {
			b.WriteString(fmt.Sprintf("  - `%s`\n", branch))
		}
	}

	if len(excluded) > 0 {
		b.WriteString("\n### Excluded Stacks\n\n")
		for _, ex := range excluded {
			b.WriteString(fmt.Sprintf("- **%s** — %s\n", ex.Stack.RootBranch, ex.Reason))
		}
	}

	b.WriteString("\n---\n")
	b.WriteString("Generated by `stackit merge --multi-stack`\n")

	return b.String()
}

// CreateAndPushBranch creates a named branch at the current HEAD and pushes it
func (p *MultiStackPRCreator) CreateAndPushBranch(ctx context.Context, branchName string) error {
	// Create a branch at current HEAD
	if err := p.worktreeEng.CreateBranch(ctx, branchName, "HEAD"); err != nil {
		return fmt.Errorf("failed to create branch %s: %w", branchName, err)
	}

	// Checkout the new branch
	branch := p.worktreeEng.GetBranch(branchName)
	if err := p.worktreeEng.CheckoutBranch(ctx, branch); err != nil {
		return fmt.Errorf("failed to checkout branch %s: %w", branchName, err)
	}

	// Push to remote
	remote := p.worktreeEng.GetRemote()
	if err := p.worktreeEng.PushBranch(ctx, branch, remote, git.PushOptions{
		Force:    false,
		NoVerify: true,
	}); err != nil {
		return fmt.Errorf("failed to push branch %s: %w", branchName, err)
	}

	return nil
}

// CreatePR creates the multi-stack pull request
func (p *MultiStackPRCreator) CreatePR(ctx context.Context, branchName string, included []MultiStackInfo, excluded []MultiStackExcluded) (*github.PullRequestInfo, error) {
	if p.ctx.GitHubClient == nil {
		return nil, fmt.Errorf("GitHub client not available")
	}

	owner, repo := p.ctx.GitHubClient.GetOwnerRepo()
	if owner == "" || repo == "" {
		return nil, fmt.Errorf("could not determine repository owner/name")
	}

	title := p.generateTitle(included)
	body := GenerateMultiStackPRBody(included, excluded)

	opts := github.CreatePROptions{
		Title: title,
		Body:  body,
		Head:  branchName,
		Base:  p.worktreeEng.Trunk().GetName(),
		Draft: false,
	}

	pr, err := p.ctx.GitHubClient.CreatePullRequest(ctx, owner, repo, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to create PR: %w", err)
	}

	return pr, nil
}

// generateTitle creates the PR title from included stacks
func (p *MultiStackPRCreator) generateTitle(included []MultiStackInfo) string {
	if len(included) == 0 {
		return "[Multi-Stack] Empty merge"
	}

	if len(included) == 1 {
		return fmt.Sprintf("[Multi-Stack] %s", included[0].RootBranch)
	}

	if len(included) == 2 {
		return fmt.Sprintf("[Multi-Stack] %s + %s", included[0].RootBranch, included[1].RootBranch)
	}

	return fmt.Sprintf("[Multi-Stack] %s + %s + %d more",
		included[0].RootBranch, included[1].RootBranch, len(included)-2)
}

// WaitAndMerge waits for CI to pass and auto-merges the PR
func (p *MultiStackPRCreator) WaitAndMerge(ctx context.Context, branchName string, pr *github.PullRequestInfo) error {
	if p.ctx.GitHubClient == nil {
		return fmt.Errorf("GitHub client not available for wait")
	}

	// Load config for merge method
	cfg, err := config.LoadConfig(p.ctx.RepoRoot)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	mergeMethod := github.MergeMethodSquash // default
	if method := cfg.MergeMethod(); method != "" {
		switch method {
		case "merge":
			mergeMethod = github.MergeMethodMerge
		case "rebase":
			mergeMethod = github.MergeMethodRebase
		}
	}

	waiter := NewCIWaiter(CIWaiterOptions{
		Client: p.ctx.GitHubClient,
		Output: p.ctx.Output,
	})

	return waiter.WaitAndMerge(ctx, branchName, pr, true, mergeMethod)
}
