package actions

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"stackit.dev/stackit/internal/engine"
	"stackit.dev/stackit/testhelpers"
	"stackit.dev/stackit/testhelpers/scenario"
)

func TestUpdatePRBodyFooter(t *testing.T) {
	footer := "\n\n\n" + sectionStart + "\n#### Stack\n\n* **PR #1** 👈\n\nThis tree was auto-generated by [Stackit](https://github.com/getstackit/stackit)\n" + sectionEnd

	t.Run("appends to empty body", func(t *testing.T) {
		result := UpdatePRBodyFooter("", footer)
		assert.Equal(t, footer, result)
	})

	t.Run("appends to existing body", func(t *testing.T) {
		body := "Original description"
		result := UpdatePRBodyFooter(body, footer)
		assert.Equal(t, body+footer, result)
	})

	t.Run("replaces existing stackit section with markers", func(t *testing.T) {
		body := "Description\n\n" + sectionStart + "\nOld Content\n" + sectionEnd + "\nFooter stuff"
		newFooter := "\n\n\n" + sectionStart + "\nNew Content\n" + sectionEnd
		result := UpdatePRBodyFooter(body, newFooter)

		assert.Contains(t, result, "Description")
		assert.Contains(t, result, "New Content")
		assert.NotContains(t, result, "Old Content")
		assert.Contains(t, result, "Footer stuff")
	})

	t.Run("idempotency - multiple updates", func(t *testing.T) {
		body := "Description"
		first := UpdatePRBodyFooter(body, footer)
		second := UpdatePRBodyFooter(first, footer)

		assert.Equal(t, first, second)
		assert.Equal(t, 1, strings.Count(second, sectionStart))
	})

	t.Run("preserves leading newlines when replacing", func(t *testing.T) {
		// Verify that we don't keep adding more newlines every time we replace
		body := "Description\n\n\n" + sectionStart + "\nContent\n" + sectionEnd
		result := UpdatePRBodyFooter(body, footer)

		// The footer constant already has 3 newlines.
		// UpdatePRBodyFooter should find the block start and replace it.
		assert.Equal(t, "Description"+footer, result)
	})
}

func TestCreatePRBodyFooter(t *testing.T) {
	t.Run("includes lock instructions when branch is locked", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Lock the branch
		_, err := s.Engine.SetLocked([]engine.Branch{s.Engine.GetBranch("feature-a")}, engine.LockReasonUser)
		require.NoError(t, err)

		footer := CreatePRBodyFooter("feature-a", s.Engine)
		assert.Contains(t, footer, "🔒 This PR has been locked (user). To unlock it, run `st unlock`.")
	})

	t.Run("does not include lock banner when branch is unlocked", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Unlocked by default
		footer := CreatePRBodyFooter("feature-a", s.Engine)
		assert.NotContains(t, footer, "🔒 This PR has been locked")
	})
}
