package actions

import (
	"fmt"
	"strings"

	"stackit.dev/stackit/internal/engine"
)

const (
	sectionStart = "<!-- STACKIT-SECTION-START -->"
	sectionEnd   = "<!-- STACKIT-SECTION-END -->"
	footerTitle  = "\n\n\n" + sectionStart + "\n#### Stack\n\n"
	footerFooter = "\n\nThis tree was auto-generated by [Stackit](https://github.com/getstackit/stackit)\n" + sectionEnd
)

// CreatePRBodyFooter creates a PR body footer with dependency tree
func CreatePRBodyFooter(branch string, eng engine.Engine) string {
	terminalParentName := findTerminalParent(branch, eng)
	terminalParent := eng.GetBranch(terminalParentName)

	var tree strings.Builder

	// Add scope if present
	scope := eng.GetScope(eng.GetBranch(branch))
	if !scope.IsEmpty() {
		tree.WriteString(fmt.Sprintf("**Scope**: %s\n\n", scope.String()))
	}

	// Add lock message if branch is locked
	if eng.GetBranch(branch).IsLocked() {
		tree.WriteString("> 🔒 This PR has been locked. To unlock it, run `st unlock`.\n\n")
	}

	for branchObj, depth := range eng.BranchesDepthFirst(terminalParent) {
		// Only include branches related to the PR branch
		if branchObj.GetName() != branch && !isParentOrChild(eng, branchObj.GetName(), branch) {
			continue // skip but continue traversal
		}

		leaf := buildLeaf(eng, branchObj.GetName(), depth, branch)
		if leaf != "" {
			tree.WriteString(leaf)
		}
	}

	return footerTitle + tree.String() + footerFooter
}

// UpdatePRBodyFooter updates an existing PR body with a new footer
func UpdatePRBodyFooter(existingBody, footer string) string {
	if existingBody == "" {
		return footer
	}

	// 1. Try markers
	if strings.Contains(existingBody, sectionStart) {
		startIdx := strings.Index(existingBody, sectionStart)
		if endIdx := strings.Index(existingBody, sectionEnd); endIdx >= 0 {
			// Find the beginning of the block (including potential leading newlines)
			blockStart := startIdx
			// Look back for up to 3 newlines
			for i := 0; i < 3; i++ {
				if blockStart > 0 && existingBody[blockStart-1] == '\n' {
					blockStart--
				} else {
					break
				}
			}
			return existingBody[:blockStart] + footer + existingBody[endIdx+len(sectionEnd):]
		}
	}

	// 2. Append footer if it doesn't exist
	return strings.TrimRight(existingBody, "\n") + footer
}

// findTerminalParent finds the terminal parent (parent of trunk) for a branch
func findTerminalParent(currentBranch string, eng engine.BranchReader) string {
	branch := eng.GetBranch(currentBranch)
	parent := branch.GetParent()
	if parent == nil {
		// No parent, use trunk
		return eng.Trunk().GetName()
	}

	if parent.IsTrunk() {
		return currentBranch
	}

	return findTerminalParent(parent.GetName(), eng)
}

// buildLeaf builds a single leaf in the tree
func buildLeaf(eng engine.Engine, branchName string, depth int, prBranch string) string {
	branch := eng.GetBranch(branchName)
	prInfo, err := branch.GetPrInfo()
	if err != nil || prInfo == nil || prInfo.Number() == nil {
		return ""
	}

	indent := strings.Repeat("  ", depth)
	marker := ""
	if branchName == prBranch {
		marker = " 👈"
	}

	return fmt.Sprintf("\n%s* **PR #%d**%s", indent, *prInfo.Number(), marker)
}

// isParentOrChild checks if branch1 is a parent or child of branch2
func isParentOrChild(eng engine.BranchReader, branch1, branch2 string) bool {
	visited := make(map[string]bool)
	return isParentOrChildRecursive(eng, branch1, branch2, visited)
}

// isParentOrChildRecursive is the recursive helper with cycle detection
func isParentOrChildRecursive(eng engine.BranchReader, branch1, branch2 string, visited map[string]bool) bool {
	// Prevent infinite recursion
	if visited[branch1] {
		return false
	}
	visited[branch1] = true

	// Check if branch1 is parent of branch2
	branch1Obj := eng.GetBranch(branch1)
	children := branch1Obj.GetChildren()
	for _, child := range children {
		if child.GetName() == branch2 {
			return true
		}
		if isParentOrChildRecursive(eng, child.GetName(), branch2, visited) {
			return true
		}
	}

	// Check if branch1 is child of branch2
	// branch1Obj already declared above
	parent := branch1Obj.GetParent()
	if parent != nil {
		if parent.GetName() == branch2 {
			return true
		}
		return isParentOrChildRecursive(eng, parent.GetName(), branch2, visited)
	}

	return false
}
