package actions

import (
	"fmt"
	"strings"

	"stackit.dev/stackit/internal/engine"
)

const (
	footerTitle  = "\n\n\n#### PR Dependency Tree\n\n"
	footerFooter = "\n\nThis tree was auto-generated by [Stackit](https://github.com/jonnii/stackit)"
)

// CreatePRBodyFooter creates a PR body footer with dependency tree
func CreatePRBodyFooter(branch string, eng engine.Engine) string {
	terminalParentName := findTerminalParent(branch, eng)
	terminalParent := eng.GetBranch(terminalParentName)

	var tree strings.Builder

	// Add scope if present
	scope := eng.GetScope(eng.GetBranch(branch))
	if !scope.IsEmpty() {
		tree.WriteString(fmt.Sprintf("**Scope**: %s\n\n", scope.String()))
	}

	for branchObj, depth := range eng.BranchesDepthFirst(terminalParent) {
		// Only include branches related to the PR branch
		if branchObj.GetName() != branch && !isParentOrChild(eng, branchObj.GetName(), branch) {
			continue // skip but continue traversal
		}

		leaf := buildLeaf(eng, branchObj.GetName(), depth, branch)
		if leaf != "" {
			tree.WriteString(leaf)
		}
	}

	return footerTitle + tree.String() + footerFooter
}

// UpdatePRBodyFooter updates an existing PR body with a new footer
func UpdatePRBodyFooter(existingBody, footer string) string {
	if existingBody == "" {
		return footer
	}

	// Check if footer already exists
	if strings.Contains(existingBody, footerTitle) {
		// Replace existing footer
		titleIndex := strings.Index(existingBody, footerTitle)
		if titleIndex >= 0 {
			// Find the end of the footer (before footerFooter)
			footerEnd := strings.Index(existingBody[titleIndex:], footerFooter)
			if footerEnd >= 0 {
				// Replace from title to end of footer
				return existingBody[:titleIndex] + footer
			}
		}
	}

	// Append footer if it doesn't exist
	return existingBody + footer
}

// findTerminalParent finds the terminal parent (parent of trunk) for a branch
func findTerminalParent(currentBranch string, eng engine.BranchReader) string {
	branch := eng.GetBranch(currentBranch)
	parent := branch.GetParent()
	if parent == nil {
		// No parent, use trunk
		return eng.Trunk().GetName()
	}

	if parent.IsTrunk() {
		return currentBranch
	}

	return findTerminalParent(parent.GetName(), eng)
}

// buildLeaf builds a single leaf in the tree
func buildLeaf(eng engine.Engine, branchName string, depth int, prBranch string) string {
	branch := eng.GetBranch(branchName)
	prInfo, err := branch.GetPrInfo()
	if err != nil || prInfo == nil || prInfo.Number() == nil {
		return ""
	}

	indent := strings.Repeat("  ", depth)
	marker := ""
	if branchName == prBranch {
		marker = " 👈"
	}

	return fmt.Sprintf("\n%s* **PR #%d**%s", indent, *prInfo.Number(), marker)
}

// isParentOrChild checks if branch1 is a parent or child of branch2
func isParentOrChild(eng engine.BranchReader, branch1, branch2 string) bool {
	visited := make(map[string]bool)
	return isParentOrChildRecursive(eng, branch1, branch2, visited)
}

// isParentOrChildRecursive is the recursive helper with cycle detection
func isParentOrChildRecursive(eng engine.BranchReader, branch1, branch2 string, visited map[string]bool) bool {
	// Prevent infinite recursion
	if visited[branch1] {
		return false
	}
	visited[branch1] = true

	// Check if branch1 is parent of branch2
	branch1Obj := eng.GetBranch(branch1)
	children := branch1Obj.GetChildren()
	for _, child := range children {
		if child.GetName() == branch2 {
			return true
		}
		if isParentOrChildRecursive(eng, child.GetName(), branch2, visited) {
			return true
		}
	}

	// Check if branch1 is child of branch2
	// branch1Obj already declared above
	parent := branch1Obj.GetParent()
	if parent != nil {
		if parent.GetName() == branch2 {
			return true
		}
		return isParentOrChildRecursive(eng, parent.GetName(), branch2, visited)
	}

	return false
}
