package actions

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"stackit.dev/stackit/testhelpers"
	"stackit.dev/stackit/testhelpers/scenario"
)

func TestUpdatePRBodyFooter(t *testing.T) {
	footer := "\n\n\n" + sectionStart + "\n#### PR Dependency Tree\n\n* **PR #1** 👈\n\nThis tree was auto-generated by [Stackit](https://github.com/getstackit/stackit)\n" + sectionEnd

	t.Run("appends to empty body", func(t *testing.T) {
		result := UpdatePRBodyFooter("", footer)
		assert.Equal(t, footer, result)
	})

	t.Run("appends to existing body", func(t *testing.T) {
		body := "Original description"
		result := UpdatePRBodyFooter(body, footer)
		assert.Equal(t, body+footer, result)
	})

	t.Run("replaces existing stackit section with markers", func(t *testing.T) {
		body := "Description\n\n" + sectionStart + "\nOld Content\n" + sectionEnd + "\nFooter stuff"
		newFooter := "\n\n\n" + sectionStart + "\nNew Content\n" + sectionEnd
		result := UpdatePRBodyFooter(body, newFooter)

		assert.Contains(t, result, "Description")
		assert.Contains(t, result, "New Content")
		assert.NotContains(t, result, "Old Content")
		assert.Contains(t, result, "Footer stuff")
	})

	t.Run("idempotency - multiple updates", func(t *testing.T) {
		body := "Description"
		first := UpdatePRBodyFooter(body, footer)
		second := UpdatePRBodyFooter(first, footer)

		assert.Equal(t, first, second)
		assert.Equal(t, 1, strings.Count(second, sectionStart))
	})

	t.Run("preserves leading newlines when replacing", func(t *testing.T) {
		// Verify that we don't keep adding more newlines every time we replace
		body := "Description\n\n\n" + sectionStart + "\nContent\n" + sectionEnd
		result := UpdatePRBodyFooter(body, footer)

		// The footer constant already has 3 newlines.
		// UpdatePRBodyFooter should find the block start and replace it.
		assert.Equal(t, "Description"+footer, result)
	})
}

func TestCreatePRBodyFooter(t *testing.T) {
	t.Run("includes lock instructions when branch is locked", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Lock the branch
		err := s.Engine.SetLocked(s.Engine.GetBranch("feature-a"), true)
		require.NoError(t, err)

		footer := CreatePRBodyFooter("feature-a", s.Engine)
		assert.Contains(t, footer, "🔒 This PR has been locked. To unlock it, run `st unlock`.")
	})

	t.Run("does not include lock banner when branch is unlocked", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Unlocked by default
		footer := CreatePRBodyFooter("feature-a", s.Engine)
		assert.NotContains(t, footer, "🔒 This PR has been locked")
	})

	t.Run("includes lock icon in tree when branches are locked", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			CreateBranch("feature-b").
			Commit("b1").
			TrackBranch("feature-a", "main").
			TrackBranch("feature-b", "feature-a")

		// Mock PR numbers
		pr1 := 1
		pr2 := 2
		require.NoError(t, s.Engine.UpsertPrInfo(s.Engine.GetBranch("feature-a"), testhelpers.NewTestPrInfo(pr1)))
		require.NoError(t, s.Engine.UpsertPrInfo(s.Engine.GetBranch("feature-b"), testhelpers.NewTestPrInfo(pr2)))

		// Lock feature-a
		require.NoError(t, s.Engine.SetLocked(s.Engine.GetBranch("feature-a"), true))

		footer := CreatePRBodyFooter("feature-b", s.Engine)

		// Check that feature-a has a lock icon and feature-b (unlocked) does not
		lines := strings.Split(footer, "\n")
		foundA := false
		foundB := false
		for _, line := range lines {
			if strings.Contains(line, "PR #1") {
				assert.Contains(t, line, "🔒")
				foundA = true
			}
			if strings.Contains(line, "PR #2") {
				assert.NotContains(t, line, "🔒")
				foundB = true
			}
		}
		assert.True(t, foundA, "did not find PR #1 in footer")
		assert.True(t, foundB, "did not find PR #2 in footer")
	})
}
