package pr

import (
	"context"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"stackit.dev/stackit/internal/engine"
	"stackit.dev/stackit/internal/git"
	"stackit.dev/stackit/testhelpers"
	"stackit.dev/stackit/testhelpers/scenario"
)

func TestUpdatePRBodyFooter(t *testing.T) {
	footer := "\n\n\n" + SectionStart + "\n#### Stack\n\n* **PR #1** 👈\n\nThis tree was auto-generated by [Stackit](https://github.com/getstackit/stackit)\n" + SectionEnd

	t.Run("appends to empty body", func(t *testing.T) {
		result := UpdatePRBodyFooter("", footer)
		assert.Equal(t, footer, result)
	})

	t.Run("appends to existing body", func(t *testing.T) {
		body := "Original description"
		result := UpdatePRBodyFooter(body, footer)
		assert.Equal(t, body+footer, result)
	})

	t.Run("replaces existing stackit section with markers", func(t *testing.T) {
		body := "Description\n\n" + SectionStart + "\nOld Content\n" + SectionEnd + "\nFooter stuff"
		newFooter := "\n\n\n" + SectionStart + "\nNew Content\n" + SectionEnd
		result := UpdatePRBodyFooter(body, newFooter)

		assert.Contains(t, result, "Description")
		assert.Contains(t, result, "New Content")
		assert.NotContains(t, result, "Old Content")
		assert.Contains(t, result, "Footer stuff")
	})

	t.Run("idempotency - multiple updates", func(t *testing.T) {
		body := "Description"
		first := UpdatePRBodyFooter(body, footer)
		second := UpdatePRBodyFooter(first, footer)

		assert.Equal(t, first, second)
		assert.Equal(t, 1, strings.Count(second, SectionStart))
	})

	t.Run("preserves leading newlines when replacing", func(t *testing.T) {
		// Verify that we don't keep adding more newlines every time we replace
		body := "Description\n\n\n" + SectionStart + "\nContent\n" + SectionEnd
		result := UpdatePRBodyFooter(body, footer)

		// The footer constant already has 3 newlines.
		// UpdatePRBodyFooter should find the block start and replace it.
		assert.Equal(t, "Description"+footer, result)
	})

	t.Run("appends footer to external PR body without markers", func(t *testing.T) {
		// Simulates a PR created outside stackit with typical content
		body := "## Summary\nThis PR adds a new feature.\n\n## Testing\n- Manual testing done"
		result := UpdatePRBodyFooter(body, footer)

		// Original content should be preserved
		assert.Contains(t, result, "## Summary")
		assert.Contains(t, result, "This PR adds a new feature.")
		assert.Contains(t, result, "## Testing")
		// Footer should be appended
		assert.Contains(t, result, SectionStart)
		assert.Contains(t, result, SectionEnd)
		// Should only have one footer
		assert.Equal(t, 1, strings.Count(result, SectionStart))
	})

	t.Run("handles body with trailing whitespace", func(t *testing.T) {
		body := "Description\n\n\n"
		result := UpdatePRBodyFooter(body, footer)

		// Trailing newlines should be trimmed before appending footer
		assert.True(t, strings.HasPrefix(result, "Description"))
		assert.Contains(t, result, SectionStart)
	})

	t.Run("handles body with only whitespace", func(t *testing.T) {
		body := "   \n\n   "
		result := UpdatePRBodyFooter(body, footer)

		// Whitespace-only body should still get footer appended
		assert.Contains(t, result, SectionStart)
	})
}

func TestCreatePRBodyFooter(t *testing.T) {
	t.Run("does NOT include lock banner (now handled independently via CreateLockSection)", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Lock the branch
		_, err := s.Engine.SetLocked(context.Background(), []engine.Branch{s.Engine.GetBranch("feature-a")}, engine.LockReasonUser)
		require.NoError(t, err)

		// Use When: "always" to ensure footer is generated for single-branch stack
		opts := NavigationOptions{When: "always", Marker: "👈"}
		footer := CreatePRBodyFooterWithOptions("feature-a", s.Engine, opts)
		// Lock is now handled separately via CreateLockSection, NOT in footer
		assert.NotContains(t, footer, "🔒 This PR has been locked")
	})
}

func TestShouldShowNavigation(t *testing.T) {
	t.Run("when=always shows navigation for single branch", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Mock a PR for the branch
		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		opts := NavigationOptions{When: "always"}
		assert.True(t, ShouldShowNavigation(opts, "feature-a", s.Engine))
	})

	t.Run("when=never hides navigation", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		opts := NavigationOptions{When: "never"}
		assert.False(t, ShouldShowNavigation(opts, "feature-a", s.Engine))
	})

	t.Run("when=multiple hides navigation for single branch", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		opts := NavigationOptions{When: "multiple"}
		assert.False(t, ShouldShowNavigation(opts, "feature-a", s.Engine))
	})

	t.Run("when=multiple shows navigation for multiple branches", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main").
			CreateBranch("feature-b").
			Commit("b1").
			TrackBranch("feature-b", "feature-a")

		// Add PRs to both branches
		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title A", "Body A", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		branch2 := s.Engine.GetBranch("feature-b")
		prNum2 := 2
		err = s.Engine.UpsertPrInfo(context.Background(), branch2, engine.NewPrInfo(&prNum2, "Title B", "Body B", "OPEN", "feature-a", "http://pr/2", false))
		require.NoError(t, err)

		opts := NavigationOptions{When: "multiple"}
		assert.True(t, ShouldShowNavigation(opts, "feature-a", s.Engine))
	})
}

func TestCreatePRBodyFooterWithOptions(t *testing.T) {
	t.Parallel()

	t.Run("includes stack description when set", func(t *testing.T) {
		t.Parallel()
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		// Set stack description
		err = s.Engine.SetStackDescription(context.Background(), branch, &git.StackDescription{
			Title:       "Auth Feature",
			Description: "OAuth2 implementation with JWT tokens",
		})
		require.NoError(t, err)

		opts := NavigationOptions{When: "always", Marker: "👈"}
		footer := CreatePRBodyFooterWithOptions("feature-a", s.Engine, opts)
		assert.Contains(t, footer, "**Auth Feature**")
		assert.Contains(t, footer, "OAuth2 implementation with JWT tokens")
	})

	t.Run("uses custom marker", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		opts := NavigationOptions{When: "always", Marker: "<--"}
		footer := CreatePRBodyFooterWithOptions("feature-a", s.Engine, opts)
		assert.Contains(t, footer, "<--")
		assert.NotContains(t, footer, "👈") // Default marker should not appear
	})

	t.Run("returns empty string when when=never", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		opts := NavigationOptions{When: "never"}
		footer := CreatePRBodyFooterWithOptions("feature-a", s.Engine, opts)
		assert.Empty(t, footer)
	})
}

func TestStripFooter(t *testing.T) {
	t.Run("removes stackit footer section", func(t *testing.T) {
		body := "Description\n\n\n" + SectionStart + "\n#### Stack\n\nContent\n" + SectionEnd
		result := StripFooter(body)
		assert.Equal(t, "Description", result)
		assert.NotContains(t, result, SectionStart)
		assert.NotContains(t, result, SectionEnd)
	})

	t.Run("returns unchanged body without footer", func(t *testing.T) {
		body := "Just a description\nwith multiple lines"
		result := StripFooter(body)
		assert.Equal(t, body, result)
	})

	t.Run("returns empty string for empty body", func(t *testing.T) {
		result := StripFooter("")
		assert.Empty(t, result)
	})

	t.Run("preserves content after footer", func(t *testing.T) {
		body := "Before\n\n\n" + SectionStart + "\nStack\n" + SectionEnd + "\nAfter"
		result := StripFooter(body)
		assert.Contains(t, result, "Before")
		assert.Contains(t, result, "After")
		assert.NotContains(t, result, SectionStart)
	})
}

func TestIsStackitComment(t *testing.T) {
	t.Run("identifies stackit navigation comment", func(t *testing.T) {
		body := CommentMarker + "\n#### Stack\n\n* **PR #1** 👈"
		assert.True(t, IsStackitComment(body))
	})

	t.Run("returns false for regular comment", func(t *testing.T) {
		body := "This is a regular comment without markers"
		assert.False(t, IsStackitComment(body))
	})

	t.Run("returns false for empty comment", func(t *testing.T) {
		assert.False(t, IsStackitComment(""))
	})
}

func TestCreateNavigationComment(t *testing.T) {
	t.Parallel()

	t.Run("includes stack description when set", func(t *testing.T) {
		t.Parallel()
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		// Set stack description
		err = s.Engine.SetStackDescription(context.Background(), branch, &git.StackDescription{
			Title:       "Auth Feature",
			Description: "OAuth2 implementation with JWT tokens",
		})
		require.NoError(t, err)

		opts := NavigationOptions{When: "always", Marker: "👈"}
		comment := CreateNavigationComment("feature-a", s.Engine, opts)
		assert.Contains(t, comment, "**Auth Feature**")
		assert.Contains(t, comment, "OAuth2 implementation with JWT tokens")
	})

	t.Run("includes comment marker", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		opts := NavigationOptions{When: "always", Marker: "👈"}
		comment := CreateNavigationComment("feature-a", s.Engine, opts)
		assert.Contains(t, comment, CommentMarker)
		assert.Contains(t, comment, "#### Stack")
		assert.Contains(t, comment, "auto-generated by")
	})

	t.Run("uses custom marker in comment", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		opts := NavigationOptions{When: "always", Marker: "<--"}
		comment := CreateNavigationComment("feature-a", s.Engine, opts)
		assert.Contains(t, comment, "<--")
	})

	t.Run("returns empty when when=never", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		opts := NavigationOptions{When: "never"}
		comment := CreateNavigationComment("feature-a", s.Engine, opts)
		assert.Empty(t, comment)
	})

	t.Run("does NOT include lock banner (now handled independently)", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		// Lock the branch
		_, err = s.Engine.SetLocked(context.Background(), []engine.Branch{branch}, engine.LockReasonUser)
		require.NoError(t, err)

		// Navigation comment should NOT contain lock message anymore
		// Lock is now handled independently via CreateLockSection
		opts := NavigationOptions{When: "always", Marker: "👈"}
		comment := CreateNavigationComment("feature-a", s.Engine, opts)
		assert.NotContains(t, comment, "🔒 This PR has been locked")
	})
}

func TestCreateLockSection(t *testing.T) {
	t.Run("returns lock section when branch is locked by user", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Lock the branch
		_, err := s.Engine.SetLocked(context.Background(), []engine.Branch{s.Engine.GetBranch("feature-a")}, engine.LockReasonUser)
		require.NoError(t, err)

		section := CreateLockSection("feature-a", s.Engine)
		assert.Contains(t, section, LockSectionStart)
		assert.Contains(t, section, LockSectionEnd)
		assert.Contains(t, section, "🔒 This PR has been locked. To unlock it, run `st unlock`.")
	})

	t.Run("returns empty string when branch is not locked", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		section := CreateLockSection("feature-a", s.Engine)
		assert.Empty(t, section)
	})

	t.Run("includes lock reason when not user-locked", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		// Lock the branch with consolidating reason
		_, err := s.Engine.SetLocked(context.Background(), []engine.Branch{s.Engine.GetBranch("feature-a")}, engine.LockReasonConsolidating)
		require.NoError(t, err)

		section := CreateLockSection("feature-a", s.Engine)
		assert.Contains(t, section, "consolidating")
	})
}

func TestUpdatePRBodyLockSection(t *testing.T) {
	lockSection := LockSectionStart + "\n> 🔒 This PR has been locked. To unlock it, run `st unlock`.\n" + LockSectionEnd

	t.Run("adds lock section to empty body", func(t *testing.T) {
		result := UpdatePRBodyLockSection("", lockSection)
		assert.Equal(t, lockSection, result)
	})

	t.Run("adds lock section at TOP of existing body", func(t *testing.T) {
		body := "## Description\nThis is my PR."
		result := UpdatePRBodyLockSection(body, lockSection)
		assert.True(t, strings.HasPrefix(result, lockSection))
		assert.Contains(t, result, "## Description")
	})

	t.Run("replaces existing lock section", func(t *testing.T) {
		oldSection := LockSectionStart + "\n> Old lock message\n" + LockSectionEnd
		body := oldSection + "\n\n## Description\nThis is my PR."
		result := UpdatePRBodyLockSection(body, lockSection)

		// Should have new lock section at top
		assert.True(t, strings.HasPrefix(result, lockSection))
		assert.Contains(t, result, "## Description")
		// Should not contain old message
		assert.NotContains(t, result, "Old lock message")
		// Should only have one lock section
		assert.Equal(t, 1, strings.Count(result, LockSectionStart))
	})

	t.Run("removes lock section when empty lockSection provided", func(t *testing.T) {
		existingLock := LockSectionStart + "\n> Lock message\n" + LockSectionEnd
		body := existingLock + "\n\n## Description\nThis is my PR."
		result := UpdatePRBodyLockSection(body, "")

		assert.NotContains(t, result, LockSectionStart)
		assert.Contains(t, result, "## Description")
	})

	t.Run("preserves navigation footer at bottom", func(t *testing.T) {
		body := "## Description\n\n\n" + SectionStart + "\n#### Stack\n\n* **PR #1** 👈\n" + SectionEnd
		result := UpdatePRBodyLockSection(body, lockSection)

		// Lock section at top
		assert.True(t, strings.HasPrefix(result, lockSection))
		// Navigation footer preserved
		assert.Contains(t, result, SectionStart)
		assert.Contains(t, result, "PR #1")
	})
}

func TestStripLockSection(t *testing.T) {
	lockSection := LockSectionStart + "\n> 🔒 This PR has been locked. To unlock it, run `st unlock`.\n" + LockSectionEnd

	t.Run("removes lock section from body", func(t *testing.T) {
		body := lockSection + "\n\n## Description\nThis is my PR."
		result := StripLockSection(body)
		assert.NotContains(t, result, LockSectionStart)
		assert.NotContains(t, result, LockSectionEnd)
		assert.Contains(t, result, "## Description")
	})

	t.Run("returns unchanged body without lock section", func(t *testing.T) {
		body := "## Description\nThis is my PR."
		result := StripLockSection(body)
		assert.Equal(t, body, result)
	})

	t.Run("returns empty string for empty body", func(t *testing.T) {
		result := StripLockSection("")
		assert.Empty(t, result)
	})

	t.Run("handles body with only lock section", func(t *testing.T) {
		result := StripLockSection(lockSection)
		assert.Empty(t, result)
	})

	t.Run("preserves navigation footer", func(t *testing.T) {
		body := lockSection + "\n\n## Description\n\n\n" + SectionStart + "\n#### Stack\n" + SectionEnd
		result := StripLockSection(body)
		assert.NotContains(t, result, LockSectionStart)
		assert.Contains(t, result, SectionStart)
	})
}

func TestLockSectionIndependentFromNavigation(t *testing.T) {
	t.Run("lock section works when navigation is hidden (single branch, when=multiple)", func(t *testing.T) {
		s := scenario.NewScenario(t, testhelpers.BasicSceneSetup)
		s.WithInitialCommit().
			CreateBranch("feature-a").
			Commit("a1").
			TrackBranch("feature-a", "main")

		branch := s.Engine.GetBranch("feature-a")
		prNum := 1
		err := s.Engine.UpsertPrInfo(context.Background(), branch, engine.NewPrInfo(&prNum, "Title", "Body", "OPEN", "main", "http://pr/1", false))
		require.NoError(t, err)

		// Lock the branch
		_, err = s.Engine.SetLocked(context.Background(), []engine.Branch{branch}, engine.LockReasonUser)
		require.NoError(t, err)

		// With when=multiple and only 1 branch, navigation should NOT show
		navOpts := NavigationOptions{When: "multiple", Marker: "👈"}
		assert.False(t, ShouldShowNavigation(navOpts, "feature-a", s.Engine))

		// But lock section should STILL be created
		lockSection := CreateLockSection("feature-a", s.Engine)
		assert.NotEmpty(t, lockSection)
		assert.Contains(t, lockSection, "🔒 This PR has been locked")
	})
}
