package pr

import (
	"fmt"
	"strings"

	"stackit.dev/stackit/internal/config"
	"stackit.dev/stackit/internal/engine"
	"stackit.dev/stackit/internal/git"
)

const (
	// SectionStart marks the beginning of the stackit-generated section in PR body.
	SectionStart = "<!-- STACKIT-SECTION-START -->"
	// SectionEnd marks the end of the stackit-generated section in PR body.
	SectionEnd = "<!-- STACKIT-SECTION-END -->"

	// LockSectionStart marks the beginning of the lock status section in PR body.
	LockSectionStart = "<!-- STACKIT-LOCK-START -->"
	// LockSectionEnd marks the end of the lock status section in PR body.
	LockSectionEnd = "<!-- STACKIT-LOCK-END -->"

	// CommentMarker is used to identify stackit-generated navigation comments.
	CommentMarker = "<!-- STACKIT-NAV-COMMENT -->"

	footerTitle  = "\n\n\n" + SectionStart + "\n#### Stack\n\n"
	footerFooter = "\n\nThis tree was auto-generated by [Stackit](https://github.com/getstackit/stackit)\n" + SectionEnd
)

// NavigationOptions controls how the stack navigation is displayed in PRs.
type NavigationOptions struct {
	// When controls when navigation is displayed: "always", "never", or "multiple"
	When string
	// Marker is the symbol used to indicate the current branch (default: "👈")
	Marker string
	// Location is where navigation appears: "body" or "comment"
	Location string
	// ShowMerged controls whether to show merged branch history
	ShowMerged bool
}

// DefaultNavigationOptions returns the default navigation options.
func DefaultNavigationOptions() NavigationOptions {
	return NavigationOptions{
		When:       config.DefaultNavigationWhen,
		Marker:     config.DefaultNavigationMarker,
		Location:   config.DefaultNavigationLocation,
		ShowMerged: config.DefaultNavigationShowMerged,
	}
}

// countStackBranches counts the number of non-trunk branches in the stack.
func countStackBranches(branch string, eng engine.BranchReader) int {
	terminalParentName := findTerminalParent(branch, eng)
	terminalParent := eng.GetBranch(terminalParentName)
	graph := engine.BuildStackGraph(eng, engine.SortStrategyAlphabetical, nil)

	count := 0
	branchRef := eng.GetBranch(branch)
	for branchObj := range eng.BranchesDepthFirst(terminalParent) {
		// Only count branches related to the PR branch
		if !graph.IsRelated(branchObj, branchRef) {
			continue
		}
		// Check if branch has a PR
		prInfo, err := branchObj.GetPrInfo()
		if err != nil || prInfo == nil || prInfo.Number() == nil {
			continue
		}
		count++
	}
	return count
}

// ShouldShowNavigation determines if navigation should be displayed based on options.
func ShouldShowNavigation(opts NavigationOptions, branch string, eng engine.BranchReader) bool {
	switch opts.When {
	case "never":
		return false
	case "multiple":
		// Only show navigation if there are 2 or more branches in the stack
		return countStackBranches(branch, eng) >= 2
	case "always":
		fallthrough
	default:
		return true
	}
}

// CreatePRBodyFooter creates a PR body footer with dependency tree using default options.
func CreatePRBodyFooter(branch string, eng engine.BranchReader) string {
	return CreatePRBodyFooterWithOptions(branch, eng, DefaultNavigationOptions())
}

// CreatePRBodyFooterWithOptions creates a PR body footer with dependency tree using custom options.
// Returns empty string if navigation should not be shown based on options.
func CreatePRBodyFooterWithOptions(branch string, eng engine.BranchReader, opts NavigationOptions) string {
	// Check if we should show navigation based on options
	if !ShouldShowNavigation(opts, branch, eng) {
		return ""
	}

	terminalParentName := findTerminalParent(branch, eng)
	terminalParent := eng.GetBranch(terminalParentName)

	// Build StackGraph for efficient traversals
	graph := engine.BuildStackGraph(eng, engine.SortStrategyAlphabetical, nil)

	var tree strings.Builder

	// Add scope if present
	scope := eng.GetScope(eng.GetBranch(branch))
	if !scope.IsEmpty() {
		fmt.Fprintf(&tree, "**Scope**: %s\n\n", scope.String())
	}

	// Note: Lock message is now handled independently via CreateLockSection()
	// to ensure it's shown even when navigation is hidden

	branchObj := eng.GetBranch(branch)

	// Add notice if present in PrInfo
	// Error is intentionally ignored: if PR info cannot be retrieved, we simply skip
	// adding the notice section, which is an optional enhancement to the footer.
	prInfo, _ := eng.GetBranch(branch).GetPrInfo()
	if prInfo != nil {
		if prInfo.MergeBranch() != "" {
			if prInfo.State() == "MERGED" {
				tree.WriteString("> 💡 **Notice**: This PR was merged via a merge branch.\n\n")
			} else {
				mergeBranch := prInfo.MergeBranch()
				msg := fmt.Sprintf("> 💡 **Notice**: This PR is part of a stack merge into branch `%s`.\n\n", mergeBranch)

				// If we can find the PR number for the merge branch, show it
				mBranch := eng.GetBranch(mergeBranch)
				if mPrInfo, err := mBranch.GetPrInfo(); err == nil && mPrInfo != nil && mPrInfo.Number() != nil {
					msg = fmt.Sprintf("> 💡 **Notice**: This PR is part of a stack merge. See PR #%d for details.\n\n", *mPrInfo.Number())
				}
				tree.WriteString(msg)
			}
		}
	}

	for b, depth := range eng.BranchesDepthFirst(terminalParent) {
		// Only include branches related to the PR branch
		if !graph.IsRelated(b, branchObj) {
			continue // skip but continue traversal
		}

		leaf := buildLeafWithMarker(eng, b.GetName(), depth, branch, opts.Marker)
		if leaf != "" {
			tree.WriteString(leaf)
		}
	}

	// Add merged downstack history if enabled
	if opts.ShowMerged {
		mergedHistory := branchObj.GetMergedDownstack()
		if len(mergedHistory) > 0 {
			tree.WriteString("\n\n**Previously based on:**")
			// Display in reverse order (oldest first)
			for i := len(mergedHistory) - 1; i >= 0; i-- {
				mp := mergedHistory[i]
				if mp.PRNumber != nil {
					tree.WriteString(fmt.Sprintf("\n* ~~PR #%d~~ (merged)", *mp.PRNumber))
				}
			}
		}
	}

	return footerTitle + tree.String() + footerFooter
}

// UpdatePRBodyFooter updates an existing PR body with a new footer.
func UpdatePRBodyFooter(existingBody, footer string) string {
	if existingBody == "" {
		return footer
	}

	// 1. Try markers
	if strings.Contains(existingBody, SectionStart) {
		startIdx := strings.Index(existingBody, SectionStart)
		if endIdx := strings.Index(existingBody, SectionEnd); endIdx >= 0 {
			// Find the beginning of the block (including potential leading newlines)
			blockStart := startIdx
			// Look back for up to 3 newlines
			for i := 0; i < 3; i++ {
				if blockStart > 0 && existingBody[blockStart-1] == '\n' {
					blockStart--
				} else {
					break
				}
			}
			return existingBody[:blockStart] + footer + existingBody[endIdx+len(SectionEnd):]
		}
	}

	// 2. Append footer if it doesn't exist
	return strings.TrimRight(existingBody, "\n") + footer
}

// StripFooter removes the stackit-generated footer from a PR body.
func StripFooter(body string) string {
	if body == "" || !strings.Contains(body, SectionStart) {
		return body
	}

	startIdx := strings.Index(body, SectionStart)
	if endIdx := strings.Index(body, SectionEnd); endIdx >= 0 {
		// Find the beginning of the block (including potential leading newlines)
		blockStart := startIdx
		// Look back for up to 3 newlines
		for i := 0; i < 3; i++ {
			if blockStart > 0 && body[blockStart-1] == '\n' {
				blockStart--
			} else {
				break
			}
		}
		return strings.TrimRight(body[:blockStart]+body[endIdx+len(SectionEnd):], "\n")
	}

	return body
}

// CreateLockSection creates an independent lock status section for the PR body.
// Returns empty string if the branch is not locked.
// This section is independent of navigation settings and appears at the TOP of the PR body.
func CreateLockSection(branch string, eng engine.BranchReader) string {
	branchObj := eng.GetBranch(branch)
	if !branchObj.IsLocked() {
		return ""
	}

	reason := branchObj.GetLockReason()
	var message string
	if reason == git.LockReasonUser {
		message = "> 🔒 This PR has been locked. To unlock it, run `st unlock`."
	} else {
		message = fmt.Sprintf("> 🔒 This PR has been locked (%s). To unlock it, run `st unlock`.", reason)
	}

	return LockSectionStart + "\n" + message + "\n" + LockSectionEnd
}

// UpdatePRBodyLockSection adds, updates, or removes the lock section at the TOP of a PR body.
// If lockSection is empty, any existing lock section is removed.
// The lock section always appears at the very top of the body.
func UpdatePRBodyLockSection(existingBody, lockSection string) string {
	// First strip any existing lock section
	body := StripLockSection(existingBody)

	// If no lock section to add, return the stripped body
	if lockSection == "" {
		return body
	}

	// Add lock section at the TOP
	if body == "" {
		return lockSection
	}

	return lockSection + "\n\n" + body
}

// StripLockSection removes the lock status section from a PR body.
func StripLockSection(body string) string {
	if body == "" || !strings.Contains(body, LockSectionStart) {
		return body
	}

	startIdx := strings.Index(body, LockSectionStart)
	endIdx := strings.Index(body, LockSectionEnd)
	if endIdx < 0 {
		return body
	}

	// Remove the lock section and any trailing newlines
	before := body[:startIdx]
	after := body[endIdx+len(LockSectionEnd):]

	// Trim leading newlines from the part after the section
	after = strings.TrimPrefix(after, "\n")
	after = strings.TrimPrefix(after, "\n")

	// Combine, trimming any trailing newlines from before
	result := strings.TrimRight(before, "\n")
	if result == "" {
		return strings.TrimLeft(after, "\n")
	}
	if after == "" {
		return result
	}
	return result + "\n" + after
}

// CreateNavigationComment creates the content for a navigation comment.
// This uses the same content as the body footer but with a comment marker.
func CreateNavigationComment(branch string, eng engine.BranchReader, opts NavigationOptions) string {
	if !ShouldShowNavigation(opts, branch, eng) {
		return ""
	}

	// Build the same tree content as the body footer but for a comment
	terminalParentName := findTerminalParent(branch, eng)
	terminalParent := eng.GetBranch(terminalParentName)
	graph := engine.BuildStackGraph(eng, engine.SortStrategyAlphabetical, nil)

	var tree strings.Builder
	tree.WriteString(CommentMarker + "\n")
	tree.WriteString("#### Stack\n\n")

	// Add scope if present
	scope := eng.GetScope(eng.GetBranch(branch))
	if !scope.IsEmpty() {
		fmt.Fprintf(&tree, "**Scope**: %s\n\n", scope.String())
	}

	// Note: Lock message is now handled independently via CreateLockSection()
	// to ensure it's shown even when navigation is hidden

	branchObj := eng.GetBranch(branch)

	// Add notice if present in PrInfo
	prInfo, _ := branchObj.GetPrInfo()
	if prInfo != nil {
		if prInfo.MergeBranch() != "" {
			if prInfo.State() == "MERGED" {
				tree.WriteString("> 💡 **Notice**: This PR was merged via a merge branch.\n\n")
			} else {
				mergeBranch := prInfo.MergeBranch()
				msg := fmt.Sprintf("> 💡 **Notice**: This PR is part of a stack merge into branch `%s`.\n\n", mergeBranch)

				// If we can find the PR number for the merge branch, show it
				mBranch := eng.GetBranch(mergeBranch)
				if mPrInfo, err := mBranch.GetPrInfo(); err == nil && mPrInfo != nil && mPrInfo.Number() != nil {
					msg = fmt.Sprintf("> 💡 **Notice**: This PR is part of a stack merge. See PR #%d for details.\n\n", *mPrInfo.Number())
				}
				tree.WriteString(msg)
			}
		}
	}

	// Build tree
	for b, depth := range eng.BranchesDepthFirst(terminalParent) {
		if !graph.IsRelated(b, branchObj) {
			continue
		}

		leaf := buildLeafWithMarker(eng, b.GetName(), depth, branch, opts.Marker)
		if leaf != "" {
			tree.WriteString(leaf)
		}
	}

	// Add merged downstack history if enabled
	if opts.ShowMerged {
		mergedHistory := branchObj.GetMergedDownstack()
		if len(mergedHistory) > 0 {
			tree.WriteString("\n\n**Previously based on:**")
			for i := len(mergedHistory) - 1; i >= 0; i-- {
				mp := mergedHistory[i]
				if mp.PRNumber != nil {
					fmt.Fprintf(&tree, "\n* ~~PR #%d~~ (merged)", *mp.PRNumber)
				}
			}
		}
	}

	tree.WriteString("\n\n_This comment was auto-generated by [Stackit](https://github.com/getstackit/stackit)_")
	return tree.String()
}

// IsStackitComment checks if a comment body is a stackit navigation comment.
func IsStackitComment(body string) bool {
	return strings.Contains(body, CommentMarker)
}

// findTerminalParent finds the terminal parent (parent of trunk) for a branch.
func findTerminalParent(currentBranch string, eng engine.BranchReader) string {
	branch := eng.GetBranch(currentBranch)
	parent := branch.GetParent()
	if parent == nil {
		// No parent, use trunk
		return eng.Trunk().GetName()
	}

	if parent.IsTrunk() {
		return currentBranch
	}

	return findTerminalParent(parent.GetName(), eng)
}

// buildLeafWithMarker builds a single leaf in the tree with a custom marker.
func buildLeafWithMarker(eng engine.BranchReader, branchName string, depth int, prBranch string, customMarker string) string {
	branch := eng.GetBranch(branchName)
	prInfo, err := branch.GetPrInfo()
	if err != nil || prInfo == nil || prInfo.Number() == nil {
		return ""
	}

	indent := strings.Repeat("  ", depth)
	marker := ""
	if branchName == prBranch {
		marker = " " + customMarker
	}

	return fmt.Sprintf("\n%s* **PR #%d**%s", indent, *prInfo.Number(), marker)
}
